services:
    repository.product:
        class: AppBundle\Repository\Product\ProductRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Product\Product

    query.doctrine_products:
        class: AppBundle\Product\Query\DoctrineProducts
        arguments:
            - "@repository.product"
            - "@knp_paginator"
