services:
    repository.product:
        class: AppBundle\Repository\Product\ProductRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Product\Product

    query.doctrine_products:
        class: AppBundle\Product\Query\DoctrineProducts
        arguments:
            - "@repository.product"
            - "@knp_paginator"

    handler.create_product:
        class: AppBundle\Product\Handler\CreateProductCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
            - "@event_dispatcher"
        tags:
            - { name: tactician.handler, command: AppBundle\Product\Command\CreateProductCommand }

    listener.product_created:
        class: AppBundle\Product\Listener\ProductCreatedListener
        arguments:
            - "@notification.sender"
            - "%product_notification_recipient%"
        tags:
            - { name: kernel.event_listener, event: product.created, method: onProductCreatedAction }

    notification.sender:
        class: AppBundle\Notification\Sender\NotificationSender
        arguments:
            - "@mailer"
            - "%email_from%"