services:
    repository.product:
        class: AppBundle\Repository\Product\ProductRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Product\Product

    query.doctrine_products:
        class: AppBundle\Product\Query\DoctrineProducts
        arguments:
            - "@repository.product"
            - "@knp_paginator"

    handler.create_product:
        class: AppBundle\Product\Handler\CreateProductCommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@validator"
        tags:
            - { name: tactician.handler, command: AppBundle\Product\Command\CreateProductCommand }
